# Generated by Django 4.1.3 on 2022-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='owner',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
