# Generated by Django 4.1.3 on 2022-11-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_district_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.CharField(default='nimadir', max_length=255),
            preserve_default=False,
        ),
    ]
