# Generated by Django 4.1.3 on 2022-11-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_district_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, choices=[('OLD', 'eski viloyatlar'), ('NEW', 'yangi viloyatlar')], default='OLD', max_length=255, null=True),
        ),
    ]
