# Generated by Django 4.1.3 on 2022-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_blog_remove_district_region_remove_hero_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default='blogs/default.png', upload_to='blogs/'),
        ),
    ]
